### ISSUE TITLE
Set up auth

### ISSUE THREAD

**Issue by ariannedee** [ariannedee/Stochastica#11]
Users
Login

**Comment by ariannedee** [comment]
@danbolinson I've updated the code so that authorization works. But we don't have registration yet.

Can you pull the code and test to make sure it works? If it does, move this issue to "Done" in the V0 project.

**Comment by danbolinson** [comment]
Worked, nice!

I added a bulk_add_images function to models but I am still struggling with
this 'located outside base path component' error. I think I am going to
format an old laptop with linux but that'll take time... can you please try
running bulk_add_images when you get a second?

Thanks,

Dan
