### ISSUE TITLE
Set up Sqlite db

### ISSUE THREAD

**Issue by ariannedee** [ariannedee/Stochastica#12]
Tables:
images - url
packs - image_pk
subscribed to - user_id, pack_id
users - name, email, password, avatar, stats: num_games, slides viewed

all have: created_at, modified_at, deleted

**Comment by ariannedee** [comment]
Can you commit your changes? That way I can check the models and migrations before migrating? You also don't have to create a users table for now, since Django creates one automatically.

**Comment by danbolinson** [comment]
done
